import { jobChatTarget, writeLineGroupSlots, type LineBakeBatch } from './chat-bake';

type Entry = { plan?: LineBakeBatch; ready: Promise<void>; resolve: () => void; ended: boolean };

/** Shared by one streaming reply; generated bytes remain in the asset store. */
export class StreamLineAttachments {
  private entries = new Map<string,Entry>();
  private ids: string[] = [];
  private target?: ReturnType<typeof jobChatTarget>;
  private insertion?: Promise<void>;
  private finishing = false;
  private failure?: unknown;
  private resolveFinished!: () => void;
  private finished = new Promise<void>(resolve=>{this.resolveFinished=resolve;});
  inserted = false;
  stats() {
    const entries=[...this.entries.values()];
    return {batches:entries.length,tagged:entries.filter(entry=>entry.plan || entry.ended).length,
      total:entries.reduce((n,entry)=>n+(entry.plan?.shots.length || 0),0),
      done:entries.reduce((n,entry)=>n+(entry.plan?.completed.size || 0),0),
      settled:entries.filter(entry=>entry.ended).length,
      failed:entries.filter(entry=>entry.ended && (!entry.plan || entry.plan.completed.size<entry.plan.shots.length)).length,
      inserted:this.inserted};
  }
  add(id: string): void {
    let resolve!: () => void;
    const ready=new Promise<void>(r=>{resolve=r;});
    this.entries.set(id,{ready,resolve,ended:false});
  }
  plan(id: string, plan: LineBakeBatch): void {
    const entry=this.entries.get(id);if(!entry)return;
    entry.plan=plan;entry.resolve();
  }
  releaseTag(id: string): void { this.entries.get(id)?.resolve(); }
  settle(id: string): void {
    const entry=this.entries.get(id);if(!entry)return;
    entry.ended=true;entry.resolve();
    if(this.inserted)void this.finalize();
  }
  waitTags(ids: string[]): Promise<unknown> {return Promise.all(ids.map(id=>this.entries.get(id)?.ready));}
  insert(ids: string[],target: ReturnType<typeof jobChatTarget>): Promise<void> {
    if(this.insertion)return this.insertion;
    this.ids=ids;this.target=target;
    this.insertion=(async()=>{
      await writeLineGroupSlots(target,this.plans());
      this.inserted=true;
      const repaint=Reflect.get(globalThis,'__OMNI_REPAINT_SPINNER_PREVIEWS__');
      // SafeDOM previews are best effort; they cannot invalidate durable placement.
      if(typeof repaint==='function')try {await repaint(ids);} catch { /* Host remount retries. */ }
      await this.finalize();
    })().catch(error=>{this.failure=error;this.resolveFinished();throw error;});
    return this.insertion;
  }
  private plans(): LineBakeBatch[] {
    return this.ids.flatMap(id=>{const plan=this.entries.get(id)?.plan;return plan?[plan]:[];});
  }
  private async finalize(): Promise<void> {
    if(this.finishing || !this.target || !this.ids.every(id=>this.entries.get(id)?.ended))return;
    this.finishing=true;
    try {
      await writeLineGroupSlots(this.target,this.plans(),true);
    } catch(error) {this.failure=error;}
    finally {this.resolveFinished();}
  }
  async waitFinished(): Promise<void> {await this.finished;if(this.failure)throw this.failure;}
}
