/**
 * Image delivery to the UI.
 *
 * Display URLs must be `data:image/…`. SafeDOM runs `setInnerHTML` through
 * DOMPurify, which strips `blob:`. `setAttribute('src', …)` is not an escape
 * hatch either — SafeElement only allows `x-*` attributes, so the call throws.
 *
 * The cache is therefore the whole design. `resolveImageUrl` is synchronous
 * because the UI calls it during render and cannot await; it returns only what
 * is already cached. Anything missing is warmed in the background at low
 * concurrency, so a gallery of 200 images paints immediately from cache and
 * fills in progressively instead of blocking on 200 decodes.
 */

import { dbg, dbgSpan } from '../core/debug';
import { abToBase64, bytesToDataUrlAsync, sniffImageMime } from '../core/util/bytes';
import { sleep } from '../core/util/async';
import { encodeGenerationWebp, type GenerationEncodingOptions } from '../domain/nai-meta/encode-generation';
import { workPool } from '../core/util/work-pool';
import { dropBlobUrl, getBlobUrl, idbGet, idbPut, pinBlobUrls, retainBlobUrls, setBlobUrl } from './stores';
import { notifyImageUrl, subscribeImageUrl as subscribeUrl, type ImageUrlListener } from './image-url-subs';

/**
 * Encodes in flight, by id.
 *
 * `stores.hydrating` already dedupes the storage read, but not the encode: the
 * viewer arrow asks for its main image directly (`ensureImageUrl`) while
 * `warmVisibleImages` queues the same id, and each caller ran its own
 * FileReader pass. Two multi-MB strings for one id, the loser garbage the
 * moment the winner landed in the cache — on a phone mid-generation that is
 * the peak that tips the tab over.
 */
const encoding = new Map<string, Promise<string>>();
let encodeCount = 0;
let encodeJoins = 0;

export interface ImageUrlStats {
  /** Encodes actually run since boot (or the last reset). */
  encodes: number;
  /** Callers that found an encode already in flight and waited on it instead. */
  encode_joins: number;
  encode_inflight: number;
  warm_queue: number;
  warm_active: number;
  warm_waiters: number;
  warm_focus: number;
}

/** Cheap integer counters for the debug snapshot; safe to call from a timer. */
export function imageUrlStats(): ImageUrlStats {
  return {
    encodes: encodeCount,
    encode_joins: encodeJoins,
    encode_inflight: encoding.size,
    warm_queue: warmQueue.length,
    warm_active: warmActive,
    warm_waiters: warmWaiters.size,
    warm_focus: warmFocus?.size ?? 0,
  };
}

/** Tests only — the counters are module state and outlive `resetStores()`. */
export function resetImageUrlStats(): void {
  encodeCount = 0;
  encodeJoins = 0;
}

/** Resolves an id to a display URL (`data:image`), reusing the cache. Returns '' when absent. */
export function ensureBlobUrl(id: string): Promise<string> {
  if (!id) return Promise.resolve('');
  const cached = getBlobUrl(id);
  if (cached !== undefined) return Promise.resolve(cached);
  const inflight = encoding.get(id);
  if (inflight) {
    encodeJoins += 1;
    return inflight;
  }
  const task = encodeDataUrl(id).finally(() => {
    encoding.delete(id);
  });
  encoding.set(id, task);
  return task;
}

async function encodeDataUrl(id: string): Promise<string> {
  encodeCount += 1;
  const span = dbgSpan('image.data_url');
  const rec = await idbGet('images', id);
  if (!rec?.png) {
    span.end({ message: `missing png ${id}`, id, background: true }, 'warn');
    return '';
  }
  const mime = (typeof rec.mime === 'string' && rec.mime) || sniffImageMime(rec.png);
  const url = await bytesToDataUrlAsync(rec.png, mime);
  if (!url) {
    span.end({ message: `encode failed ${id}`, id, bytes: rec.png.byteLength || 0, mime }, 'warn');
    return '';
  }
  setBlobUrl(id, url, rec.png.byteLength || 0);
  // Inline shots placed their markers before this finished. Tell that one cell
  // its bytes arrived instead of making it re-run the whole paint pass.
  notifyImageUrl(id, url);
  span.end({ message: id, bytes: rec.png.byteLength || 0, mime, url_len: url.length, focus: true });
  return url;
}

/**
 * Notifies `cb(id, url)` as each id becomes displayable, replaying ids that are
 * already cached. Returns an unsubscribe that the caller must run.
 */
export function subscribeImageUrl(ids: unknown, cb: ImageUrlListener): () => void {
  return subscribeUrl(ids, cb, (id) => getBlobUrl(id) || '');
}

/** Cache-only lookup. Safe to call from synchronous UI render paths. */
export function resolveImageUrl(cardOrId: unknown): string {
  const id = typeof cardOrId === 'string' ? cardOrId : (cardOrId as { id?: unknown } | null)?.id;
  if (!id) return '';
  return getBlobUrl(String(id)) || '';
}

/**
 * Stores generated bytes and returns a displayable URL.
 *
 * Re-encodes to WebP first: at quality 0.9 it is typically much smaller than PNG
 * while staying sharper than 0.8. NovelAI PNG text chunks are dropped on
 * purpose — the module store is display bytes, not a metadata sidecar.
 * Bytes go to the gallery module when the host can save assets. If the
 * browser cannot encode WebP we keep the incoming bytes rather than fail.
 */
const encodePublishedImage = workPool(2);
export async function publishImage(
  id: string,
  png: ArrayBuffer,
  location: Record<string, unknown> | null = null,
  options: GenerationEncodingOptions & { warmUrl?: boolean; onPreview?: (url: string) => Promise<void> } = {},
): Promise<string> {
  const span = dbgSpan('image.publish');
  dropBlobUrl(id);
  // Paint the paid result before WebP encoding or asset registration can wait.
  let previewUrl = '';
  if (options.onPreview) {
    previewUrl = await bytesToDataUrlAsync(png, sniffImageMime(png));
    setBlobUrl(id, previewUrl, png.byteLength);
    await options.onPreview(previewUrl);
  }
  let bytes: ArrayBuffer = png;
  let mime = sniffImageMime(png);
  try {
    const webp = await encodePublishedImage(() => encodeGenerationWebp(png, options));
    if (webp) {
      bytes = webp;
      mime = sniffImageMime(webp);
    }
  } catch (err) {
    dbg('image.webp', { message: String((err as Error)?.message || err), id }, 'warn');
  }
  await idbPut('images', { id, png: bytes, mime, location: location || {}, asset_only: true });
  if (previewUrl) return previewUrl;
  if (options.warmUrl === false) {
    span.end({message:id,bytes:bytes.byteLength,mime,has_url:false,asset_only:true});
    return '';
  }

  // The encode can stall on a busy main thread. Wait briefly so the common case
  // returns a ready URL, then hand off rather than blocking the job.
  let url = '';
  try {
    const pending = ensureBlobUrl(id);
    url = await Promise.race([pending, sleep(5000).then(() => resolveImageUrl(id) || '')]);
    if (!url) {
      dbg('image.data_url.defer', { message: id, bytes: bytes?.byteLength || 0, mime, focus: true }, 'warn');
      pending.catch((err: unknown) =>
        console.warn('[Inlay Nexus] deferred data URL failed', (err as Error)?.message || err),
      );
    }
  } catch (err) {
    dbg('image.data_url', { message: String((err as Error)?.message || err), id }, 'warn');
    Promise.resolve()
      .then(() => ensureBlobUrl(id))
      .catch(() => {});
  }
  span.end({
    message: id,
    bytes: bytes?.byteLength || 0,
    src_bytes: png?.byteLength || 0,
    mime,
    has_url: Boolean(url),
    has_location: Boolean(location && Object.keys(location).length),
    focus: true,
  });
  return url;
}

// ── background warming ──────────────────────────────────────────────────────

/**
 * Four at a time: enough to hide latency behind the UI's own render work, low
 * enough that warming a large gallery never starves an in-flight generation.
 *
 * It was two while `warmImages` ran its own parallel chunks — effective
 * concurrency was closer to six, unordered. Now that every encode goes through
 * the one queue below, this number is the whole throughput budget.
 */
const WARM_CONCURRENCY = 4;

const warmQueued = new Set<string>();
const warmQueue: string[] = [];
/**
 * Callers waiting on a specific id. This is what makes one queue enough:
 * `warmImages` used to bypass it and encode in its own parallel chunks, so
 * `prioritizeWarmFocus` reordered a queue that the busiest caller never read
 * and the selected bubble competed on equal terms with the explorer strip.
 */
const warmWaiters = new Map<string, Array<() => void>>();
/**
 * Ids the current selection wants first.
 *
 * Priority only — it moves them to the front of the queue and scopes the mint
 * toast's progress. It used to be a monopoly that parked everything else, with
 * a 40ms poll that could hold a non-focus encode for 90 seconds; moving the
 * selection then swapped the focus set and stalled the bubble the user had just
 * left. Two encode slots are not worth arbitrating that hard over.
 */
let warmFocus: Set<string> | null = null;
let warmActive = 0;
/** Lifetime counters for the current warm wave (reset when the queue drains). */
let warmWaveTotal = 0;
let warmWaveDone = 0;
let warmNotify: (() => void) | null = null;

export interface WarmProgress {
  pending: number;
  active: number;
  done: number;
  total: number;
  pct: number;
  busy: boolean;
}

/** Snapshot of background image-indexing (data-URL encode) progress. */
export function warmProgress(): WarmProgress {
  const pending = warmQueue.length + warmActive;
  const total = Math.max(warmWaveTotal, warmWaveDone + pending);
  const done = Math.min(warmWaveDone, total);
  const pct = total > 0 ? Math.max(0, Math.min(100, Math.round((done / total) * 100))) : 0;
  return { pending, active: warmActive, done, total, pct, busy: pending > 0 };
}

/**
 * Selection-focus warm only — drives the mint progress toast.
 * Full-gallery / deferred background warm must NOT keep that toast alive.
 */
export function warmFocusProgress(): WarmProgress {
  if (!warmFocus?.size) {
    return { pending: 0, active: 0, done: 0, total: 0, pct: 0, busy: false };
  }
  let done = 0;
  for (const id of warmFocus) {
    if (getBlobUrl(id) !== undefined) done += 1;
  }
  const total = warmFocus.size;
  const pending = Math.max(0, total - done);
  const pct = total > 0 ? Math.max(0, Math.min(100, Math.round((done / total) * 100))) : 0;
  const busy = pending > 0;
  return {
    pending,
    active: busy ? Math.min(warmActive, pending) : 0,
    done,
    total,
    pct: busy ? Math.max(6, pct) : pct,
    busy,
  };
}

/** UI hooks this to repaint the dual status bars while images index. */
export function onWarmProgress(fn: (() => void) | null): void {
  warmNotify = typeof fn === 'function' ? fn : null;
}

function notifyWarm(): void {
  try {
    warmNotify?.();
  } catch {
    /* UI paint must never break the warm pump */
  }
}

/** Encode these ids first and scope the mint toast to them. Nothing is parked. */
export function prioritizeWarmFocus(ids: unknown[] = []): void {
  const list = [...new Set((ids || []).map(String).filter(Boolean))];
  pinBlobUrls(list);
  const want = list.filter((id) => getBlobUrl(id) === undefined);
  const front: string[] = [];
  for (const id of want) {
    if (!warmQueued.has(id)) {
      warmQueued.add(id);
      warmWaveTotal += 1;
    }
    front.push(id);
  }
  const rest = warmQueue.filter((id) => !front.includes(id));
  warmQueue.length = 0;
  warmQueue.push(...front, ...rest);
  warmFocus = want.length ? new Set(want) : null;
  notifyWarm();
  pumpWarm();
}

/** Ends the selection-scoped progress readout. Queue order is left as-is. */
export function clearWarmFocus(): void {
  warmFocus = null;
  notifyWarm();
}

/**
 * Releases everyone awaiting this id.
 *
 * Must run on every exit an id can take, not just a finished encode: an id with
 * no bytes resolves to '' and never notifies a URL, and `pinImageUrls` /
 * `retainImageUrls` evict queued ids outright. Missing either case leaves a
 * `warmImages` caller awaiting forever.
 */
function settleWarm(id: string): void {
  const waiters = warmWaiters.get(id);
  if (!waiters) return;
  warmWaiters.delete(id);
  for (const done of waiters) {
    try {
      done();
    } catch {
      /* one waiter must not strand the rest */
    }
  }
}

/** Queues one id and resolves when it has been encoded, or given up on. */
function warmOne(id: string): Promise<void> {
  if (!id || getBlobUrl(id) !== undefined) return Promise.resolve();
  const wait = new Promise<void>((resolve) => {
    const waiters = warmWaiters.get(id);
    if (waiters) waiters.push(resolve);
    else warmWaiters.set(id, [resolve]);
  });
  if (!warmQueued.has(id)) {
    warmQueued.add(id);
    warmQueue.push(id);
    warmWaveTotal += 1;
    notifyWarm();
    pumpWarm();
  }
  return wait;
}

function pumpWarm(): void {
  while (warmActive < WARM_CONCURRENCY && warmQueue.length) {
    const id = warmQueue.shift() as string;
    warmActive += 1;
    notifyWarm();
    ensureBlobUrl(id)
      .catch(() => {})
      .finally(() => {
        warmActive -= 1;
        warmQueued.delete(id);
        settleWarm(id);
        warmWaveDone += 1;
        if (warmFocus?.has(id)) warmFocus.delete(id);
        if (warmFocus && !warmFocus.size) warmFocus = null;
        if (warmQueue.length === 0 && warmActive === 0) {
          // Hold totals so UI can paint ~100% once before the wave clears.
          notifyWarm();
          setTimeout(() => {
            if (warmQueue.length === 0 && warmActive === 0) {
              warmWaveTotal = 0;
              warmWaveDone = 0;
              notifyWarm();
            }
          }, 180);
        } else {
          notifyWarm();
          pumpWarm();
        }
      });
  }
}

export function enqueueWarm(id: unknown): void {
  void warmOne(String(id || ''));
}

/**
 * Pin sticky-window ids against LRU eviction and pull them to the front of the
 * warm queue so returning to a message is not stuck behind a long gallery encode.
 */
export function pinImageUrls(ids: unknown[] = []): void {
  const list = [...new Set((ids || []).map(String).filter(Boolean))];
  pinBlobUrls(list);
  if (!list.length) return;
  const pinned = new Set(list);
  const prevPending = warmQueue.length;
  const kept: string[] = [];
  for (const id of warmQueue) {
    if (pinned.has(id)) kept.push(id);
    else {
      warmQueued.delete(id);
      settleWarm(id);
    }
  }
  warmQueue.length = 0;
  const front: string[] = [];
  for (const id of list) {
    if (getBlobUrl(id) !== undefined) continue;
    if (!warmQueued.has(id)) {
      warmQueued.add(id);
      warmWaveTotal += 1;
    }
    if (!front.includes(id)) front.push(id);
  }
  const rest = kept.filter((id) => !front.includes(id));
  warmQueue.push(...front, ...rest);
  const dropped = prevPending - kept.length;
  if (dropped > 0 && !warmFocus?.size) {
    warmWaveTotal = Math.max(warmWaveDone + warmQueue.length + warmActive, warmWaveTotal - dropped);
  }
  notifyWarm();
  pumpWarm();
}

/**
 * Explorer folder hops: keep only these data-URLs in memory and cancel warm work
 * for everything else, so revisiting 통합보기 does not reuse a huge resident set.
 */
export function retainImageUrls(ids: unknown[] = []): void {
  const list = [...new Set((ids || []).map(String).filter(Boolean))];
  retainBlobUrls(list);
  const keep = new Set(list);
  for (const id of warmQueue) {
    if (keep.has(id)) continue;
    warmQueued.delete(id);
    settleWarm(id);
  }
  const next = warmQueue.filter((id) => keep.has(id));
  warmQueue.length = 0;
  warmQueue.push(...next);
  pinImageUrls(list);
}

/** Drop one cached data-URL (explorer may release thumbs when leaving a folder). */
export function dropImageUrl(id: unknown): void {
  dropBlobUrl(String(id || ''));
}

/**
 * Warms a batch and returns the URLs that resolved.
 *
 * Queues through `warmOne` rather than encoding here. Encoding here was its own
 * second encoder with its own slots, which is why the inline bubble's
 * `prioritizeWarmFocus` had no effect on the explorer and viewer strips racing
 * it — they all called this.
 */
export async function warmImages(ids: unknown[] = []): Promise<string[]> {
  const list = [...new Set((ids || []).map(String).filter(Boolean))];
  const need = list.filter((id) => getBlobUrl(id) === undefined);
  if (need.length) await Promise.all(need.map((id) => warmOne(id)));
  return list.map((id) => resolveImageUrl(id)).filter(Boolean);
}

export interface AttachUrlOptions {
  /** Only these ids are encoded synchronously; the rest use cache + warming. */
  ids?: Iterable<unknown>;
  /** Never encode synchronously. The gallery list default. */
  cachedOnly?: boolean;
  /**
   * When false, missing URLs stay empty and are NOT queued for background encode.
   * Explorer lists hundreds of rows and only warms the visible window itself —
   * enqueueing every miss here freezes Chrome on refresh.
   */
  warmMissing?: boolean;
}

/**
 * Walks a response payload and fills in `image_url` on anything card-shaped.
 *
 * Mutates in place, matching 1.x: these are freshly built response objects, and
 * copying them would double peak memory for a payload that already carries
 * hundreds of data URLs.
 */
export async function attachImageUrls<T>(obj: T, opts: AttachUrlOptions = {}): Promise<T> {
  if (!obj || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) {
    for (let i = 0; i < obj.length; i += 1) obj[i] = await attachImageUrls(obj[i], opts);
    return obj;
  }
  const rec = obj as Record<string, unknown>;
  const isCard =
    typeof rec.id === 'string' &&
    (typeof rec.image_url === 'string' || rec.image_path != null || 'shot_index' in rec || 'main_prompt' in rec);
  if (isCard) {
    const id = String(rec.id);
    const filter = opts.ids != null ? new Set([...opts.ids].map(String)) : null;
    const eager = !opts.cachedOnly && (!filter || filter.has(id));
    if (eager) {
      const url = await ensureBlobUrl(id);
      if (url) rec.image_url = url;
    } else {
      rec.image_url = resolveImageUrl(id) || '';
      if (!rec.image_url && opts.warmMissing !== false) enqueueWarm(id);
    }
    return obj;
  }
  for (const key of Object.keys(rec)) {
    if (rec[key] && typeof rec[key] === 'object') {
      rec[key] = await attachImageUrls(rec[key], opts);
    }
  }
  return obj;
}

/** Synchronous data URL for the two singleton preview images held in memory. */
export function pngToDataUrl(png: ArrayBuffer | null | undefined): string {
  if (!png) return '';
  return `data:${sniffImageMime(png)};base64,${abToBase64(png)}`;
}
